In [55]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder, LabelEncoder,StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix


In [56]:
df=pd.read_csv(r'C:\Datasets\Covid_dataset.csv')

In [57]:
X=df.iloc[:, :-1].values
Y=df.iloc[:, -1].values


In [58]:
print(X)


[[10.0 'Moderate' 'no' 'no' 97.0]
 [12.0 'Moderate' 'no' 'no' 97.0]
 [15.0 'Moderate' 'no' 'no' 94.0]
 [10.0 'Moderate' 'no' 'no' 97.0]
 [13.0 'Moderate' 'no' 'no' 94.0]
 [12.0 'Moderate' 'no' 'no' 97.0]
 [13.0 'Moderate' 'no' 'no' 93.0]
 [15.0 'Moderate' 'no' 'no' 92.0]
 [18.0 'Moderate' 'no' 'no' 66.0]
 [19.0 'Moderate' 'no' 'no' 92.0]
 [20.0 'Moderate' 'no' 'no' 93.0]
 [17.0 'Moderate' 'no' 'no' 93.0]
 [16.0 'Moderate' 'no' 'no' 92.0]
 [18.0 'Moderate' 'no' 'no' 93.0]
 [20.0 'Moderate' 'no' 'no' 92.0]
 [25.0 'Moderate' 'no' 'no' 93.0]
 [24.0 'Moderate' 'no' 'no' 92.0]
 [26.0 'High' 'no' 'no' 94.0]
 [28.0 'Moderate' 'no' 'no' 99.0]
 [29.0 'Moderate' 'no' 'no' 93.0]
 [30.0 'Moderate' 'no' 'no' 62.0]
 [19.0 'Moderate' 'no' 'no' 89.0]
 [25.0 'Moderate' 'no' 'yes' 86.0]
 [26.0 'Moderate' 'no' 'no' nan]
 [28.0 'Moderate' 'no' 'no' 89.0]
 [30.0 'Moderate' 'yes' 'no' 86.0]
 [35.0 'Moderate' 'no' 'no' 89.0]
 [32.0 'Moderate' 'no' 'yes' 84.0]
 [nan 'Moderate' 'yes' 'no' 90.0]
 [32.0 'Moderate

In [59]:
print(Y)

['No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'Yes' 'No' 'No' 'No' 'No' 'No'
 'No' 'No' 'No' 'No' 'No' 'No' 'Yes' 'No' 'No' 'No' 'No' 'No' 'No' 'No'
 'No' 'No' 'No' 'Yes' 'No' 'No' 'No' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes'
 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes'
 'No' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'No' 'Yes' 'Yes' 'Yes' 'Yes'
 'Yes' 'No' 'Yes' 'Yes' 'Yes']


In [60]:
imputer=SimpleImputer(missing_values=np.nan,strategy='mean')
imputer.fit(X[:,0:1])
X[: , 0:1]=imputer.transform(X[: ,0:1])

print(X)

[[10.0 'Moderate' 'no' 'no' 97.0]
 [12.0 'Moderate' 'no' 'no' 97.0]
 [15.0 'Moderate' 'no' 'no' 94.0]
 [10.0 'Moderate' 'no' 'no' 97.0]
 [13.0 'Moderate' 'no' 'no' 94.0]
 [12.0 'Moderate' 'no' 'no' 97.0]
 [13.0 'Moderate' 'no' 'no' 93.0]
 [15.0 'Moderate' 'no' 'no' 92.0]
 [18.0 'Moderate' 'no' 'no' 66.0]
 [19.0 'Moderate' 'no' 'no' 92.0]
 [20.0 'Moderate' 'no' 'no' 93.0]
 [17.0 'Moderate' 'no' 'no' 93.0]
 [16.0 'Moderate' 'no' 'no' 92.0]
 [18.0 'Moderate' 'no' 'no' 93.0]
 [20.0 'Moderate' 'no' 'no' 92.0]
 [25.0 'Moderate' 'no' 'no' 93.0]
 [24.0 'Moderate' 'no' 'no' 92.0]
 [26.0 'High' 'no' 'no' 94.0]
 [28.0 'Moderate' 'no' 'no' 99.0]
 [29.0 'Moderate' 'no' 'no' 93.0]
 [30.0 'Moderate' 'no' 'no' 62.0]
 [19.0 'Moderate' 'no' 'no' 89.0]
 [25.0 'Moderate' 'no' 'yes' 86.0]
 [26.0 'Moderate' 'no' 'no' nan]
 [28.0 'Moderate' 'no' 'no' 89.0]
 [30.0 'Moderate' 'yes' 'no' 86.0]
 [35.0 'Moderate' 'no' 'no' 89.0]
 [32.0 'Moderate' 'no' 'yes' 84.0]
 [45.130434782608695 'Moderate' 'yes' 'no' 90.0]
 

In [61]:
imputer.fit(X[:,4:5])
X[: , 4:5]=imputer.transform(X[: ,4:5])

print(X)

[[10.0 'Moderate' 'no' 'no' 97.0]
 [12.0 'Moderate' 'no' 'no' 97.0]
 [15.0 'Moderate' 'no' 'no' 94.0]
 [10.0 'Moderate' 'no' 'no' 97.0]
 [13.0 'Moderate' 'no' 'no' 94.0]
 [12.0 'Moderate' 'no' 'no' 97.0]
 [13.0 'Moderate' 'no' 'no' 93.0]
 [15.0 'Moderate' 'no' 'no' 92.0]
 [18.0 'Moderate' 'no' 'no' 66.0]
 [19.0 'Moderate' 'no' 'no' 92.0]
 [20.0 'Moderate' 'no' 'no' 93.0]
 [17.0 'Moderate' 'no' 'no' 93.0]
 [16.0 'Moderate' 'no' 'no' 92.0]
 [18.0 'Moderate' 'no' 'no' 93.0]
 [20.0 'Moderate' 'no' 'no' 92.0]
 [25.0 'Moderate' 'no' 'no' 93.0]
 [24.0 'Moderate' 'no' 'no' 92.0]
 [26.0 'High' 'no' 'no' 94.0]
 [28.0 'Moderate' 'no' 'no' 99.0]
 [29.0 'Moderate' 'no' 'no' 93.0]
 [30.0 'Moderate' 'no' 'no' 62.0]
 [19.0 'Moderate' 'no' 'no' 89.0]
 [25.0 'Moderate' 'no' 'yes' 86.0]
 [26.0 'Moderate' 'no' 'no' 82.07246376811594]
 [28.0 'Moderate' 'no' 'no' 89.0]
 [30.0 'Moderate' 'yes' 'no' 86.0]
 [35.0 'Moderate' 'no' 'no' 89.0]
 [32.0 'Moderate' 'no' 'yes' 84.0]
 [45.130434782608695 'Moderate' 'yes

In [90]:
ct=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[1])],remainder='passthrough')
X=np.array(ct.fit_transform(X))


In [91]:
print(X)

[[0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [1. 0. 1. 1. 1.]
 [0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [1. 0. 1. 1. 1.]
 [0. 1. 0. 0. 0.]
 [1. 0. 1. 1. 1.]
 [0. 1. 0. 0. 0.]
 [1. 0. 1. 1. 1.]
 [1. 0. 1. 1. 1.]
 [0. 1. 0. 0. 0.]
 [1. 0. 1. 1. 1.]
 [1. 0. 1. 1. 1.]
 [1. 0. 1. 1. 1.]
 [1. 0. 1. 1. 1.]
 [1. 0. 1. 1. 1.]
 [1. 0. 1. 1. 1.]
 [1. 0. 1. 1. 1.]
 [1. 0. 1. 1. 1.]
 [1. 0. 1. 1. 1.]
 [1. 0. 1. 1. 1.]
 [1. 0. 1. 1. 1.]
 [1. 0. 1. 1. 1.]
 [1. 0. 1. 1. 1.]
 [1. 0. 1. 1. 1.]
 [1. 0. 1. 1. 1.]
 [0. 1. 0. 0. 0.]
 [1. 0. 1. 1. 1.]
 [1. 0. 1.

In [92]:
le=LabelEncoder()
Y=le.fit_transform(Y)

In [93]:
x_train,x_test,y_train,y_test=train_test_split(X,Y,train_size=0.8,random_state=42)


In [94]:

print(x_test)

[[0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [1. 0. 1. 1. 1.]
 [0. 1. 0. 0. 0.]
 [1. 0. 1. 1. 1.]
 [0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [1. 0. 1. 1. 1.]
 [1. 0. 1. 1. 1.]
 [0. 1. 0. 0. 0.]
 [1. 0. 1. 1. 1.]
 [0. 1. 0. 0. 0.]
 [1. 0. 1. 1. 1.]
 [0. 1. 0. 0. 0.]]


In [104]:
print(X.shape)

(70, 5)


In [98]:
sc=StandardScaler()
x_train[: , 4:]=sc.fit_transform(x_train[: , 4:])
x_test[: , 4:]=sc.fit_transform(x_test[: , 4:])



In [99]:
print(x_train)

[[ 1.          0.          1.          1.          0.96490128]
 [ 0.          1.          0.          0.         -1.03637545]
 [ 1.          0.          1.          1.          0.96490128]
 [ 1.          0.          1.          1.          0.96490128]
 [ 1.          0.          1.          1.          0.96490128]
 [ 1.          0.          1.          1.          0.96490128]
 [ 0.          1.          0.          0.         -1.03637545]
 [ 0.          1.          0.          0.         -1.03637545]
 [ 1.          0.          1.          1.          0.96490128]
 [ 0.          1.          0.          0.         -1.03637545]
 [ 0.          1.          0.          0.         -1.03637545]
 [ 0.          1.          0.          0.         -1.03637545]
 [ 1.          0.          1.          1.          0.96490128]
 [ 1.          0.          1.          1.          0.96490128]
 [ 1.          0.          1.          1.          0.96490128]
 [ 0.          1.          0.          0.         -1.03

In [100]:
model = LogisticRegression()
model.fit(x_train, y_train)
y_pred = model.predict(x_test)
accuracy = accuracy_score(y_test, y_pred)
print(f"Model Accuracy: {accuracy * 100:.2f}%")


Model Accuracy: 92.86%


In [101]:
print("Classification Report:")
print(classification_report(y_test, y_pred))
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.89      0.94         9
           1       0.83      1.00      0.91         5

    accuracy                           0.93        14
   macro avg       0.92      0.94      0.93        14
weighted avg       0.94      0.93      0.93        14

Confusion Matrix:
[[8 1]
 [0 5]]
